#!/bin/bash

psql maps <<EOF
DROP TABLE if exists Symbols_GA;

CREATE TABLE Symbols_GA (
  name text,
  body text,
  dependencies text
);

-- GRANT select ON Symbols_GA TO ro;
EOF

cat symbols/* | psql maps
